### PR TITLE
opaque.h header does not compile in C++ environment

### PR DESCRIPTION
**Pull request by WorldofJARcraft**
The expression
```c
uint8_t sec[OPAQUE_USER_SESSION_SECRET_LEN+pwdU_len]
```
in opaque.h is valid in C, but does not compile in C++ since the compiler does not know what `pwdU_len` will be at run time.
I have changed the type to pointer and left the expected size as a comment.

### CODE REVIEW

**Comment by stef** [comment]
why would you compile this with c++?

**Comment by WorldofJARcraft** [comment]
I have a mixed code base with both C and C++.
I included opaque.h from a C++ source file (as a meta-dependency), and it broke my build since C++ did not understand the two method declarations that followed the schema above.

**Comment by stef** [comment]
and linking as a static lib (compiled by c not c++) or explicitly saying that opaque needs gcc instead of g++ is no solution?

**Comment by stef** [comment]
i think there is a way to use the cpp to distinguish between c and c++ compiler maybe use 
```
#ifdef c++
.... just pointer
#else
... original array with size
#endif
```

**Comment by WorldofJARcraft** [comment]
> i think there is a way to use the cpp to distinguish between c and c++ compiler maybe use
> 
> ```
> #ifdef c++
> .... just pointer
> #else
> ... original array with size
> #endif
> ```

The latest change should do that, currently testing it in my CI.

**Comment by stef** [comment]
awesome! :)

**Pull request merged**
