### PR TITLE
Compiling on Windows (MinGW)

### PR DESCRIPTION
**Pull request by tibotix**
To compile libopaque on windows with MinGW, the following steps had to be done:

- renaming the `aux` directory to `aux_`, as AUX is a reserved file/directory name in Windows.
- add a seperate makefile.windows that changes some compiler flags (e.g. `-z relro` does not exist in MinGW)  , changes SOEXT to dll and add a linker flag to link agains `-lws2_32` (winsocks2 lib)
- add preprocessor check in `opaque.c` to conditionally include `winsock2.h` instead of `arpa/inet.h` for the htons function

Things that do not compile under Windows are:

- `utils/main.c` executable, as it uses some specific `fcntl()` calls that do not exist in windows.

Note that iam not very familiar with the linker options provided by MinGW and which one is responsible for extra security features. However, this is the output of winchecksec against the compiled `libopaque.dll` lib:

```
Warn: No load config in the PE
Results for: ./libopaque.dll
Dynamic Base    : "Present"
ASLR            : "Present"
High Entropy VA : "Present"
Force Integrity : "NotPresent"
Isolation       : "Present"
NX              : "Present"
SEH             : "Present"
CFG             : "NotPresent"
RFG             : "NotPresent"
SafeSEH         : "NotApplicable"
GS              : "NotPresent"
Authenticode    : "NotPresent"
.NET            : "NotPresent"
```

### CODE REVIEW

**Comment by stef** [comment]
awesome. instead of a seperate makefile you can have a look at how we handle different archs/os in a sister projects makefile: https://github.com/stef/libsphinx/blob/master/src/makefile

and maybe call the target mingw instead of windows, maybe someone comes along and adds a visualc port or so...

**Comment by stef** [comment]
btw the `fcntl`s are used for checking if a filedescriptor is open/exists, if you know a replacement for that in mingw perhaps?

**Comment by tibotix** [comment]
As far as I know, MinGW has a `_fstat` function that expects an open file descriptor and some buffer and returns `-1` if the file status information could not be obtained and `0` if it could be obtained. maybe this is useful...

**Comment by tibotix** [comment]
I changed `utils/main.c` to use the `_fstat` function. It now compiles under MinGW and runs. However i have not checked the functionality of the WindowsAPI call yet.

**Comment by stef** [comment]
love it! are you sure you're only 18?

**Comment by stef** [comment]
love it! are you sure you're only 18?

**Comment by stef** [comment]
btw also added a note to the main readme about your dart binding...

**Pull request merged**
