### PR TITLE
Js app infos update

### PR DESCRIPTION
**Pull request by stef**
please have a look @creemama at my feeble attempt at updating the js bindings. i have no emscripten environment, so i couldn't test this.

basically what it boils down to, is that the app_infos only has one `info` and one `einfo` field, and `userauth` does not receive an `appinfos` structure as a parameter anymore.

happy to learn from your fixes to this, how to work this wrapper so i can be more independent the next time.

thank you very much for all your kind support!

### CODE REVIEW

**Comment by stef** [comment]
hmm, the checks failed. hrmpf. will have a look at this tomorrow. now zzzzz

**Comment by creemama** [comment]
@stef, `js/wrapper/libopaque-pre.js` is where all the magic happens.

There's no need to update the files in `dist` manually. Running `make` generates `dist`'s contents.

I was eyeing to make this change to `info` myself. I'm glad I held off.

**Review by creemama — COMMENTED** [review]
See https://github.com/stef/libopaque/pull/19#issuecomment-777169065.

**Comment by stef** [comment]
i see. thank you for fixing my mess again :)

i wonder, why do we have generated files in the gitrepo? can we remove everything that can be generated via  the makefile? or why is this a bad idea?

**Comment by creemama** [comment]
Unlike other languages, including [compiled JavaScript source in a `dist` directory](https://gist.github.com/tracker1/59f2c13044315f88bee9) is not uncommon for JavaScript projects. See the following Git repos:
* https://github.com/jedisct1/libsodium.js/tree/master/dist
* https://github.com/jashkenas/underscore
* https://github.com/dimsemenov/PhotoSwipe/tree/master/dist
* https://github.com/cytoscape/cytoscape.js/tree/unstable/dist
* https://github.com/SheetJS/sheetjs/tree/master/dist

For us, the benefit of doing this is making the JavaScript and PHP demos easier to run. Setting up and compiling using Emscripten is a little painful.

**Pull request merged**
